### ISSUE TITLE
Ucinanie tekstu - remove duplicates, numbers to word

### ISSUE THREAD

**Issue by bonczol** [kamieen03/Projekt-IO#4]
Chyba jest jakiś problem z tymi dwoma funkcjami. Jak wkleiłem Lorem ipsum to czasami ucinają tekst dziwnie. Nie wiem czy to wina kropek?

**Comment by kamieen03** [comment]
Chyba coś po stronie JSa, bo te metody wcale nie dostają kropki, jeśli jest ostatnia
